kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: my-cluster
networking:
  apiServerPort: 6443
nodes:
- role: control-plane
  image: kindest/node:v1.34.0
  extraPortMappings:
    - containerPort: 30080
      hostPort: 18080
      protocol: TCP
- role: worker
  image: kindest/node:v1.34.0
  extraMounts:
    - hostPath: ${COMMON_PATH}/k8s/spark
      containerPath: /spark
    - hostPath: ${COMMON_PATH}/k8s/scylladb
      containerPath: /scylladb